# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19tjqMB7cu31OHD6dN5XZ1wPMMVFCeHp2
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("sales.csv")

data.head()

data.info()

data.isnull().sum()

data.dropna(inplace=True)
 data.info()

data["Amount"].dtype

data["Product_ID"].dtype

data["Orders"].dtype

data["Order"] = data["Orders"].astype("int8")

data["Amount"].describe()

#EDA

data["Gender"].value_counts()

data["Gender"].value_counts().plot(kind="pie",autopct="%0.2f%%")
plt.show()

data.groupby("Gender")["Amount"].sum()

data.groupby("Gender")["Amount"].sum().plot(kind="pie",autopct="%0.2f%%")
plt.show()

data["Gender"].value_counts().plot(kind="bar",color=("pink","blue"))
plt.title("Coustomer divided by Gender")
plt.show()

data["Age Group"].value_counts().plot(kind="bar")
plt.title("Coustomer divided by age")
plt.show()

data.groupby("Age Group")["Amount"].sum().plot(kind="bar")
plt.title("Coustmer divided by spending & Age")
plt.show()

data["Marital_Status"].value_counts().plot(kind="pie",autopct="%0.0f%%")
plt.title("Marid v Unmarid")
plt.show()

data["State"].value_counts().plot(kind="bar")
plt.title("Coustmer from different state")
plt.show()

data["Amount"].plot(kind="hist",bins=range(0,25000,2500),edgecolor="black")
plt.xticks(range(0,25000,2500))
plt.show()

data["Occupation"].value_counts().plot(kind="bar")
plt.show()

data["Zone"].value_counts().plot(kind="bar")
plt.show()

#Conclusion

# Married Woman b/w 26-35 Years From UP, Maharastra , karnataka Working in IT
#Healthcare and more
#like to Buy Product Are Food , Clothing And Electronics Category .

data.columns

data["Product_Category"].value_counts()

data["Occupation"].value_counts()

data["Zone"].value_counts()

